#
# Ref:
#  - https://docs.travis-ci.com/user/job-lifecycle/
#

language: python
jobs:
  include:
  - name: "Python 2.7"
    python: "2.7"
    dist: xenial
  - name: "Python 3.6"
    python: "3.6"
    dist: trusty
    allow_failures: true
  - name: "Python 3.7"
    python: "3.7"
    dist: trusty
    allow_failures: true

  - name: "Python 3.8 on Xenial (Ubuntu 16.04)"
    python: "3.8"
    dist: xenial
  - name: "Python 3.8 on Bionic (Ubuntu 18.04)"
    python: "3.8"
    dist: bionic

  - name: "Python 3.9 on Xenial (Ubuntu 16.04)"
    python: "3.9"
    dist: xenial
  - name: "Python 3.9 on Bionic (Ubuntu 18.04)"
    python: "3.9"
    dist: bionic

#virtualenv:
#  system_site_packages: true

# before_install:

# Ref:
#  = https://github.com/travis-ci/travis-ci/issues/2870
#  - https://docs.travis-ci.com/user/job-lifecycle/
#  - https://docs.travis-ci.com/user/deployment/script/
install:
  - pip install build --upgrade
  - make build

# before_script:

script:
    - pip install -r requirements.txt

# after_success:

# after_failure:

#
# Deployment
#

# before_deploy:

# deploy:

# after_deploy:

# after_script:
