language: python
python:
    - "2.7"
    - "3.6"
    - "3.9"

# Ref:
#  = https://github.com/travis-ci/travis-ci/issues/2870
#  - https://docs.travis-ci.com/user/job-lifecycle/
#  - https://docs.travis-ci.com/user/deployment/script/
install:
    - make build
script:
    - pip install -r requirements.txt
